import React, { useState } from 'react';
import { 
  ShieldAlert, 
  AlertTriangle, 
  Phone, 
  CheckCircle2, 
  Clock, 
  MapPin, 
  User, 
  Car, 
  Siren, 
  Search, 
  Filter, 
  Plus, 
  X, 
  MessageSquare,
  Navigation,
  FileText,
  ShieldCheck,
  Stethoscope,
  Wrench
} from 'lucide-react';
import { useRide } from '../../context/RideContext';
import { EmergencyRequest } from '../../types';

export const AdminEmergency: React.FC = () => {
  const { 
    emergencyRequests, 
    resolveEmergencyRequest, 
    updateEmergencyStatus, 
    triggerEmergencyRequest, 
    showNotification 
  } = useRide();

  const [searchQuery, setSearchQuery] = useState('');
  const [filterStatus, setFilterStatus] = useState<'all' | 'active' | 'responding' | 'resolved'>('all');
  const [filterType, setFilterType] = useState<string>('all');
  const [selectedEmergency, setSelectedEmergency] = useState<EmergencyRequest | null>(null);

  // Modal states for action dialogs
  const [showDispatchModal, setShowDispatchModal] = useState(false);
  const [dispatchUnit, setDispatchUnit] = useState('Metro Manila Police (PNP Desk) & SwiftRide Safety Team');
  const [showResolveModal, setShowResolveModal] = useState(false);
  const [resolutionNotes, setResolutionNotes] = useState('');

  // Simulation form state
  const [showSimulateModal, setShowSimulateModal] = useState(false);
  const [simType, setSimType] = useState<'Safety SOS' | 'Accident' | 'Medical' | 'Harassment' | 'Vehicle Breakdown' | 'Panic Button'>('Safety SOS');
  const [simRole, setSimRole] = useState<'passenger' | 'driver'>('passenger');
  const [simNotes, setSimNotes] = useState('');

  const activeCount = emergencyRequests.filter(e => e.status === 'active').length;
  const respondingCount = emergencyRequests.filter(e => e.status === 'responding').length;
  const resolvedCount = emergencyRequests.filter(e => e.status === 'resolved').length;

  const filteredRequests = emergencyRequests.filter(req => {
    const matchesStatus = filterStatus === 'all' || req.status === filterStatus;
    const matchesType = filterType === 'all' || req.emergencyType === filterType;
    const query = searchQuery.toLowerCase();
    const matchesSearch = !searchQuery || 
      req.userName.toLowerCase().includes(query) ||
      req.id.toLowerCase().includes(query) ||
      (req.driverName && req.driverName.toLowerCase().includes(query)) ||
      (req.rideId && req.rideId.toLowerCase().includes(query)) ||
      req.location.name.toLowerCase().includes(query);

    return matchesStatus && matchesType && matchesSearch;
  });

  const getEmergencyBadgeColor = (type: string) => {
    switch (type) {
      case 'Safety SOS': return 'bg-rose-500/20 text-rose-400 border-rose-500/30';
      case 'Accident': return 'bg-amber-500/20 text-amber-400 border-amber-500/30';
      case 'Medical': return 'bg-red-500/20 text-red-400 border-red-500/30';
      case 'Harassment': return 'bg-purple-500/20 text-purple-400 border-purple-500/30';
      case 'Vehicle Breakdown': return 'bg-blue-500/20 text-blue-400 border-blue-500/30';
      default: return 'bg-zinc-800 text-slate-300 border-zinc-700';
    }
  };

  const getStatusBadge = (status: EmergencyRequest['status']) => {
    switch (status) {
      case 'active':
        return (
          <span className="px-2.5 py-0.5 rounded-md text-[11px] font-semibold bg-rose-500/20 text-rose-400 border border-rose-500/30 flex items-center gap-1.5">
            <span className="w-1.5 h-1.5 rounded-full bg-rose-400"></span>
            Critical Active
          </span>
        );
      case 'responding':
        return (
          <span className="px-2.5 py-0.5 rounded-md text-[11px] font-semibold bg-amber-500/20 text-amber-400 border border-amber-500/30 flex items-center gap-1.5">
            <Siren className="w-3 h-3 text-amber-400" />
            Dispatch Responding
          </span>
        );
      case 'resolved':
        return (
          <span className="px-2.5 py-0.5 rounded-md text-[11px] font-semibold bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 flex items-center gap-1.5">
            <ShieldCheck className="w-3 h-3 text-emerald-400" />
            Resolved
          </span>
        );
      default:
        return (
          <span className="px-2.5 py-0.5 rounded-md text-[11px] font-semibold bg-zinc-800 text-slate-400">
            Dismissed
          </span>
        );
    }
  };

  const handleSimulateSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    triggerEmergencyRequest({
      userRole: simRole,
      emergencyType: simType,
      notes: simNotes || `Simulated ${simType} request generated by Admin Ops desk.`
    });
    setShowSimulateModal(false);
    setSimNotes('');
  };

  const handleConfirmDispatch = () => {
    if (selectedEmergency) {
      updateEmergencyStatus(selectedEmergency.id, 'responding', dispatchUnit);
      showNotification('Emergency Dispatch Sent', `Dispatched unit: ${dispatchUnit} for SOS #${selectedEmergency.id}`, 'warning');
      setShowDispatchModal(false);
      setSelectedEmergency(null);
    }
  };

  const handleConfirmResolve = () => {
    if (selectedEmergency) {
      resolveEmergencyRequest(selectedEmergency.id, resolutionNotes || 'Incident handled and verified resolved by Admin Operations Desk.');
      setShowResolveModal(false);
      setResolutionNotes('');
      setSelectedEmergency(null);
    }
  };

  return (
    <div className="space-y-6 max-w-7xl mx-auto pb-10">
      {/* Top Banner Stats */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="p-4 bg-zinc-950 border border-zinc-800 rounded-2xl flex items-center justify-between shadow-sm">
          <div>
            <p className="text-[11px] font-mono font-bold text-slate-400 uppercase tracking-wider">Total Emergency SOS</p>
            <p className="text-2xl font-black text-white font-display mt-1">{emergencyRequests.length}</p>
          </div>
          <div className="w-12 h-12 rounded-xl bg-zinc-900 border border-zinc-800 flex items-center justify-center text-slate-300">
            <ShieldAlert className="w-6 h-6 text-rose-400" />
          </div>
        </div>

        <div className="p-4 bg-rose-950/30 border border-rose-900/50 rounded-2xl flex items-center justify-between shadow-sm relative overflow-hidden">
          {activeCount > 0 && <span className="absolute top-0 right-0 w-full h-1 bg-rose-500 animate-pulse"></span>}
          <div>
            <p className="text-[11px] font-mono font-bold text-rose-300 uppercase tracking-wider">Active Critical SOS</p>
            <p className="text-2xl font-black text-rose-400 font-display mt-1 flex items-center gap-2">
              {activeCount}
              {activeCount > 0 && <span className="w-2.5 h-2.5 rounded-full bg-rose-500 animate-ping"></span>}
            </p>
          </div>
          <div className="w-12 h-12 rounded-xl bg-rose-500/20 border border-rose-500/30 flex items-center justify-center text-rose-400">
            <AlertTriangle className="w-6 h-6 text-rose-400 animate-bounce" />
          </div>
        </div>

        <div className="p-4 bg-amber-950/30 border border-amber-900/50 rounded-2xl flex items-center justify-between shadow-sm">
          <div>
            <p className="text-[11px] font-mono font-bold text-amber-300 uppercase tracking-wider">Units Responding</p>
            <p className="text-2xl font-black text-amber-400 font-display mt-1">{respondingCount}</p>
          </div>
          <div className="w-12 h-12 rounded-xl bg-amber-500/20 border border-amber-500/30 flex items-center justify-center text-amber-400">
            <Siren className="w-6 h-6 text-amber-400" />
          </div>
        </div>

        <div className="p-4 bg-emerald-950/30 border border-emerald-900/50 rounded-2xl flex items-center justify-between shadow-sm">
          <div>
            <p className="text-[11px] font-mono font-bold text-emerald-300 uppercase tracking-wider">Incidents Resolved</p>
            <p className="text-2xl font-black text-emerald-400 font-display mt-1">{resolvedCount}</p>
          </div>
          <div className="w-12 h-12 rounded-xl bg-emerald-500/20 border border-emerald-500/30 flex items-center justify-center text-emerald-400">
            <ShieldCheck className="w-6 h-6 text-emerald-400" />
          </div>
        </div>
      </div>

      {/* Control Bar: Filters & Simulation Button */}
      <div className="p-4 bg-zinc-950 border border-zinc-800 rounded-2xl flex flex-wrap items-center justify-between gap-4">
        {/* Search */}
        <div className="relative flex-1 min-w-[240px]">
          <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
          <input 
            type="text"
            value={searchQuery}
            onChange={e => setSearchQuery(e.target.value)}
            placeholder="Search emergency ID, user, trip, location..."
            className="w-full pl-9 pr-4 py-2 bg-zinc-900 border border-zinc-800 rounded-xl text-xs text-white placeholder-slate-500 font-mono focus:outline-none focus:ring-1 focus:ring-amber-500"
          />
        </div>

        {/* Status Pills */}
        <div className="flex items-center gap-1.5 bg-zinc-900 p-1 rounded-xl border border-zinc-800">
          {(['all', 'active', 'responding', 'resolved'] as const).map(st => (
            <button
              key={st}
              onClick={() => setFilterStatus(st)}
              className={`px-3 py-1.5 rounded-lg text-xs font-mono font-bold transition-all cursor-pointer capitalize ${
                filterStatus === st 
                  ? (st === 'active' ? 'bg-rose-500 text-white font-black' : 'bg-amber-500 text-black font-black')
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              {st === 'all' ? 'All Alerts' : st}
            </button>
          ))}
        </div>

        {/* Category Dropdown */}
        <div className="flex items-center gap-2">
          <Filter className="w-4 h-4 text-slate-400" />
          <select
            value={filterType}
            onChange={e => setFilterType(e.target.value)}
            className="bg-zinc-900 border border-zinc-800 rounded-xl px-3 py-2 text-xs font-mono text-white focus:outline-none focus:ring-1 focus:ring-amber-500"
          >
            <option value="all">All Emergency Types</option>
            <option value="Safety SOS">Safety SOS</option>
            <option value="Accident">Accident</option>
            <option value="Medical">Medical</option>
            <option value="Harassment">Harassment</option>
            <option value="Vehicle Breakdown">Vehicle Breakdown</option>
          </select>
        </div>

        {/* Trigger Test Simulation */}
        <button
          onClick={() => setShowSimulateModal(true)}
          className="flex items-center gap-2 px-4 py-2 bg-rose-600 hover:bg-rose-500 text-white font-mono font-bold rounded-xl text-xs transition-colors cursor-pointer shadow-md"
        >
          <Plus className="w-4 h-4" />
          <span>Simulate Emergency SOS</span>
        </button>
      </div>

      {/* Emergency Requests List */}
      <div className="space-y-4">
        {filteredRequests.length === 0 ? (
          <div className="p-12 text-center bg-zinc-950 border border-zinc-800 rounded-2xl space-y-3">
            <ShieldCheck className="w-12 h-12 text-emerald-400 mx-auto opacity-80" />
            <h4 className="text-sm font-bold text-white font-mono">No Emergency Alerts Found</h4>
            <p className="text-xs text-slate-500 max-w-sm mx-auto font-mono">
              There are currently no emergency notifications matching your filter criteria. All active passenger & driver dispatches are running safely.
            </p>
          </div>
        ) : (
          filteredRequests.map(req => {
            const isCritical = req.status === 'active';

            return (
              <div 
                key={req.id}
                className={`p-5 rounded-2xl border transition-all ${
                  isCritical 
                    ? 'bg-rose-950/20 border-rose-500/60 shadow-lg shadow-rose-950/50' 
                    : req.status === 'responding'
                    ? 'bg-amber-950/20 border-amber-500/40'
                    : 'bg-zinc-950 border-zinc-800'
                }`}
              >
                <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 border-b border-zinc-800/80 pb-4">
                  {/* Left Metadata Header */}
                  <div className="flex items-center gap-3">
                    <div className={`w-11 h-11 rounded-xl flex items-center justify-center shrink-0 border ${
                      isCritical ? 'bg-rose-500 text-white border-rose-400 animate-pulse' : 'bg-zinc-900 text-amber-400 border-zinc-800'
                    }`}>
                      <ShieldAlert className="w-6 h-6" />
                    </div>
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="text-xs font-mono font-black text-white">{req.id}</span>
                        <span className={`px-2 py-0.5 rounded text-[10px] font-mono font-bold border ${getEmergencyBadgeColor(req.emergencyType)}`}>
                          {req.emergencyType}
                        </span>
                        {getStatusBadge(req.status)}
                      </div>
                      <p className="text-xs text-slate-400 font-mono mt-0.5 flex items-center gap-2">
                        <span>Logged: <strong className="text-slate-200">{req.createdAt}</strong></span>
                        <span>•</span>
                        <span>Trip ID: <strong className="text-amber-400">{req.rideId || 'N/A'}</strong></span>
                      </p>
                    </div>
                  </div>

                  {/* Actions Bar */}
                  <div className="flex flex-wrap items-center gap-2">
                    <a
                      href={`tel:${req.userPhone}`}
                      className="px-3 py-1.5 bg-zinc-900 hover:bg-zinc-800 text-emerald-400 font-mono font-bold text-xs rounded-xl border border-zinc-800 flex items-center gap-1.5 transition-colors"
                    >
                      <Phone className="w-3.5 h-3.5" />
                      <span>Call User ({req.userPhone})</span>
                    </a>

                    {req.status !== 'resolved' && (
                      <button
                        onClick={() => {
                          setSelectedEmergency(req);
                          setShowDispatchModal(true);
                        }}
                        className="px-3 py-1.5 bg-amber-500/20 hover:bg-amber-500/30 text-amber-400 font-mono font-bold text-xs rounded-xl border border-amber-500/30 flex items-center gap-1.5 transition-colors cursor-pointer"
                      >
                        <Siren className="w-3.5 h-3.5" />
                        <span>Dispatch Emergency Unit</span>
                      </button>
                    )}

                    {req.status !== 'resolved' ? (
                      <button
                        onClick={() => {
                          setSelectedEmergency(req);
                          setShowResolveModal(true);
                        }}
                        className="px-3 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white font-mono font-bold text-xs rounded-xl flex items-center gap-1.5 transition-colors cursor-pointer shadow-xs"
                      >
                        <CheckCircle2 className="w-3.5 h-3.5" />
                        <span>Resolve Alert</span>
                      </button>
                    ) : (
                      <span className="text-xs font-mono text-emerald-400 font-bold flex items-center gap-1">
                        <CheckCircle2 className="w-4 h-4" /> Incident Cleared
                      </span>
                    )}
                  </div>
                </div>

                {/* Content Details Grid */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 pt-4 text-xs font-mono">
                  {/* User & Vehicle Info */}
                  <div className="bg-zinc-900/60 p-3 rounded-xl border border-zinc-800 space-y-2">
                    <p className="text-[10px] text-slate-500 uppercase font-bold tracking-wider">User Details</p>
                    <div className="flex items-center gap-2.5">
                      <img 
                        src={req.userAvatar || 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100'} 
                        alt={req.userName}
                        className="w-8 h-8 rounded-lg object-cover border border-zinc-700"
                      />
                      <div>
                        <p className="text-white font-bold">{req.userName}</p>
                        <span className={`text-[10px] uppercase font-bold px-1.5 py-0.5 rounded ${
                          req.userRole === 'driver' ? 'bg-amber-500/20 text-amber-400' : 'bg-blue-500/20 text-blue-400'
                        }`}>
                          {req.userRole}
                        </span>
                      </div>
                    </div>

                    {req.driverName && req.userRole === 'passenger' && (
                      <div className="pt-2 border-t border-zinc-800/80 text-slate-400 text-[11px] space-y-0.5">
                        <p className="text-slate-500 font-bold">Assigned Driver Partner:</p>
                        <p className="text-white font-semibold">{req.driverName} ({req.driverPhone || '0917 888 1234'})</p>
                        <p className="text-amber-400">{req.vehicleInfo}</p>
                      </div>
                    )}
                  </div>

                  {/* Location & GPS Telemetry */}
                  <div className="bg-zinc-900/60 p-3 rounded-xl border border-zinc-800 space-y-2">
                    <p className="text-[10px] text-slate-500 uppercase font-bold tracking-wider">GPS Telemetry & Location</p>
                    <div className="flex items-start gap-2">
                      <MapPin className="w-4 h-4 text-rose-400 shrink-0 mt-0.5" />
                      <div>
                        <p className="text-white font-bold">{req.location.name}</p>
                        <p className="text-slate-400 text-[11px]">{req.location.address}</p>
                        <p className="text-[10px] text-amber-400/80 font-mono mt-1">
                          Coordinates: [{req.location.lat.toFixed(4)}, {req.location.lng.toFixed(4)}]
                        </p>
                      </div>
                    </div>
                  </div>

                  {/* Incident Narrative & Responder Dispatch */}
                  <div className="bg-zinc-900/60 p-3 rounded-xl border border-zinc-800 space-y-2">
                    <p className="text-[10px] text-slate-500 uppercase font-bold tracking-wider">Incident Log & Responders</p>
                    <p className="text-slate-300 leading-relaxed text-[11px] bg-zinc-950 p-2 rounded-lg border border-zinc-800/60">
                      {req.notes || 'No extra notes provided.'}
                    </p>
                    {req.assignedResponder && (
                      <div className="text-[11px] text-amber-400 font-bold flex items-center gap-1.5 pt-1">
                        <Siren className="w-3.5 h-3.5" />
                        <span>Assigned Unit: {req.assignedResponder}</span>
                      </div>
                    )}
                  </div>
                </div>
              </div>
            );
          })
        )}
      </div>

      {/* Dispatch Modal */}
      {showDispatchModal && selectedEmergency && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-xs flex items-center justify-center p-4 z-50">
          <div className="bg-zinc-950 border border-zinc-800 rounded-3xl p-6 w-full max-w-md space-y-4 shadow-2xl">
            <div className="flex items-center justify-between border-b border-zinc-800 pb-3">
              <h4 className="text-sm font-black text-white font-mono flex items-center gap-2">
                <Siren className="w-4 h-4 text-amber-400" />
                Dispatch Emergency Responders
              </h4>
              <button onClick={() => setShowDispatchModal(false)} className="text-slate-400 hover:text-white">
                <X className="w-4 h-4" />
              </button>
            </div>

            <div className="text-xs font-mono space-y-3">
              <p className="text-slate-400">
                Sending official command dispatch for emergency request <strong className="text-white">{selectedEmergency.id}</strong> ({selectedEmergency.userName}).
              </p>

              <div>
                <label className="block text-slate-400 mb-1 font-bold">Select Response Unit / Authority:</label>
                <select
                  value={dispatchUnit}
                  onChange={e => setDispatchUnit(e.target.value)}
                  className="w-full bg-zinc-900 border border-zinc-800 rounded-xl p-2.5 text-white font-mono text-xs focus:ring-1 focus:ring-amber-500"
                >
                  <option value="Metro Manila Police (PNP Desk) & SwiftRide Safety Team">
                    PNP Police Assistance & Rapid Safety Response
                  </option>
                  <option value="MMDA Emergency Rescue & Medical Unit (911)">
                    MMDA Ambulance / Emergency Medical (911)
                  </option>
                  <option value="Metro Manila Towing & Mechanical Roadside Unit">
                    SwiftRide Mechanical Towing Unit
                  </option>
                  <option value="SwiftRide Dedicated Incident Response Patrol">
                    SwiftRide Private Fleet Patrol
                  </option>
                </select>
              </div>
            </div>

            <div className="flex items-center justify-end gap-2 pt-2">
              <button
                onClick={() => setShowDispatchModal(false)}
                className="px-4 py-2 bg-zinc-900 hover:bg-zinc-800 text-slate-400 rounded-xl font-mono text-xs font-bold"
              >
                Cancel
              </button>
              <button
                onClick={handleConfirmDispatch}
                className="px-4 py-2 bg-amber-500 hover:bg-amber-400 text-black rounded-xl font-mono text-xs font-black"
              >
                Confirm Dispatch
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Resolve Modal */}
      {showResolveModal && selectedEmergency && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-xs flex items-center justify-center p-4 z-50">
          <div className="bg-zinc-950 border border-zinc-800 rounded-3xl p-6 w-full max-w-md space-y-4 shadow-2xl">
            <div className="flex items-center justify-between border-b border-zinc-800 pb-3">
              <h4 className="text-sm font-black text-white font-mono flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                Resolve Emergency Request
              </h4>
              <button onClick={() => setShowResolveModal(false)} className="text-slate-400 hover:text-white">
                <X className="w-4 h-4" />
              </button>
            </div>

            <div className="text-xs font-mono space-y-3">
              <p className="text-slate-400">
                Marking SOS alert <strong className="text-white">{selectedEmergency.id}</strong> as safely resolved and cleared.
              </p>

              <div>
                <label className="block text-slate-400 mb-1 font-bold">Resolution Report / Notes:</label>
                <textarea
                  value={resolutionNotes}
                  onChange={e => setResolutionNotes(e.target.value)}
                  placeholder="Enter brief resolution summary (e.g. Passenger confirmed safe, situation resolved on-site by police)."
                  rows={3}
                  className="w-full bg-zinc-900 border border-zinc-800 rounded-xl p-2.5 text-white font-mono text-xs focus:ring-1 focus:ring-emerald-500"
                />
              </div>
            </div>

            <div className="flex items-center justify-end gap-2 pt-2">
              <button
                onClick={() => setShowResolveModal(false)}
                className="px-4 py-2 bg-zinc-900 hover:bg-zinc-800 text-slate-400 rounded-xl font-mono text-xs font-bold"
              >
                Cancel
              </button>
              <button
                onClick={handleConfirmResolve}
                className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white rounded-xl font-mono text-xs font-black"
              >
                Clear Alert
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Simulation Modal */}
      {showSimulateModal && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-xs flex items-center justify-center p-4 z-50">
          <form onSubmit={handleSimulateSubmit} className="bg-zinc-950 border border-zinc-800 rounded-3xl p-6 w-full max-w-md space-y-4 shadow-2xl">
            <div className="flex items-center justify-between border-b border-zinc-800 pb-3">
              <h4 className="text-sm font-black text-white font-mono flex items-center gap-2">
                <ShieldAlert className="w-4 h-4 text-rose-500" />
                Simulate User SOS Notification
              </h4>
              <button type="button" onClick={() => setShowSimulateModal(false)} className="text-slate-400 hover:text-white">
                <X className="w-4 h-4" />
              </button>
            </div>

            <div className="text-xs font-mono space-y-3">
              <div>
                <label className="block text-slate-400 mb-1 font-bold">Role Initiating SOS:</label>
                <div className="grid grid-cols-2 gap-2">
                  <button
                    type="button"
                    onClick={() => setSimRole('passenger')}
                    className={`py-2 rounded-xl text-center font-bold border transition-colors cursor-pointer ${
                      simRole === 'passenger' ? 'bg-amber-500 text-black border-amber-500' : 'bg-zinc-900 text-slate-400 border-zinc-800'
                    }`}
                  >
                    Passenger
                  </button>
                  <button
                    type="button"
                    onClick={() => setSimRole('driver')}
                    className={`py-2 rounded-xl text-center font-bold border transition-colors cursor-pointer ${
                      simRole === 'driver' ? 'bg-amber-500 text-black border-amber-500' : 'bg-zinc-900 text-slate-400 border-zinc-800'
                    }`}
                  >
                    Driver Partner
                  </button>
                </div>
              </div>

              <div>
                <label className="block text-slate-400 mb-1 font-bold">Emergency Incident Type:</label>
                <select
                  value={simType}
                  onChange={e => setSimType(e.target.value as any)}
                  className="w-full bg-zinc-900 border border-zinc-800 rounded-xl p-2.5 text-white font-mono text-xs focus:ring-1 focus:ring-rose-500"
                >
                  <option value="Safety SOS">Safety SOS (Urgent Threat)</option>
                  <option value="Accident">Accident / Collision</option>
                  <option value="Medical">Medical Emergency</option>
                  <option value="Harassment">Harassment / Altercation</option>
                  <option value="Vehicle Breakdown">Vehicle Mechanical Breakdown</option>
                  <option value="Panic Button">Panic Button Triggered</option>
                </select>
              </div>

              <div>
                <label className="block text-slate-400 mb-1 font-bold">Simulated Incident Description:</label>
                <textarea
                  value={simNotes}
                  onChange={e => setSimNotes(e.target.value)}
                  placeholder="Optional incident details (e.g. Passenger feels unsafe during night trip)."
                  rows={2}
                  className="w-full bg-zinc-900 border border-zinc-800 rounded-xl p-2 text-white font-mono text-xs focus:ring-1 focus:ring-rose-500"
                />
              </div>
            </div>

            <div className="flex items-center justify-end gap-2 pt-2">
              <button
                type="button"
                onClick={() => setShowSimulateModal(false)}
                className="px-4 py-2 bg-zinc-900 hover:bg-zinc-800 text-slate-400 rounded-xl font-mono text-xs font-bold"
              >
                Cancel
              </button>
              <button
                type="submit"
                className="px-4 py-2 bg-rose-600 hover:bg-rose-500 text-white rounded-xl font-mono text-xs font-black shadow-md"
              >
                Trigger SOS Alert
              </button>
            </div>
          </form>
        </div>
      )}
    </div>
  );
};
